# Generated by Django 4.1.3 on 2022-11-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[(1, 'Плохо!'), (2, 'Неплохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=5, max_length=10),
        ),
    ]
