# Generated by Django 4.1.3 on 2022-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('Плохо!', 'Плохо!'), ('Неплохо', 'Неплохо'), ('Нормально', 'Нормально'), ('Хорошо', 'Хорошо'), ('Отлично', 'Отлично')], default=5, max_length=10),
        ),
    ]
